/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_putao_jnidemo_PrivSdkClient */

#ifndef _Included_com_putao_jnidemo_PrivSdkClient
#define _Included_com_putao_jnidemo_PrivSdkClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_putao_jnidemo_PrivSdkClient
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_putao_jnidemo_PrivSdkClient_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
